### ISSUE TITLE
"error":"connect: does not exist (Connection refused)","details":{}

### ISSUE THREAD

**Issue by Jipperism** [mvoidex/hsdev#22] opened 2016-01-23 12:42 UTC
Hi, I've been recieving an error message upon tring to setup the hsdev package. It seems to not be able to connect. Info:

> $ hsdev version
> 0.1.5.2
> $ hsdev start
> Server started at port 4567
> $ hsdev ping
> {"error":"connect: does not exist (Connection refused)","details":{}}

I have also tried `$ hsdev start --cache cache` but to no avail. Any other commands return the same error message.

**Comment by mvoidex** [comment] 2016-01-23 16:34
Seems, that `hsdev` can't start. `hsdev run` fails on Ubuntu

**Comment by Jipperism** [comment] 2016-01-23 17:49
What is the easiest way of updating my version to this new commit? And thanks a bunch for the quick response.

**Comment by mvoidex** [comment] 2016-01-23 17:53
It's not fixed yet. I'll upload new version on hackage when done

**Comment by mvoidex** [comment] 2016-01-23 21:40
Please check [hsdev-0.1.5.3](http://hackage.haskell.org/package/hsdev-0.1.5.3)
Works for me on Ubuntu

**Comment by Jipperism** [comment] 2016-01-23 22:57
I have upgraded to hsdev-0.1.5.3, and everything is working now. Thanks! Some more output from ST3 console that might be of interest:

```
Sublime Haskell: failed to connect to hsdev server
Sublime Haskell: connected to hsdev server
Sublime Haskell: Inspection failed: 'HsDev' object has no attribute 'hsdev_socket'
Sublime Haskell: loading standard modules info for cabal failed with 'HsDev' object has no attribute 'hsdev_socket'
Sublime Haskell: connecting to hsdev server...
Sublime Haskell: connected to hsdev server
Package Control: No updated packages
Sublime Haskell: hsdev ghc-mod type returns error: File '/home/jip/Code/Haskell/petProject/src/Main.hs' not found, details: {}
unknown include #infix_op
unknown include #infix_op
unknown include #comments
unknown include #common_keywords
unknown include #literals
unknown include #quasi_quote
unknown include #ctor_names
unknown include #comments
unknown include #common_keywords
unknown include #literals
unknown include #quasi_quote
unknown include #ctor_names
```

It seems to work now tho, i think this issue can be closed. I can insert types and use auto-fix, so I guess everything should be working. Thanks!

**Comment by mvoidex** [comment] 2016-01-23 23:09
Good!
But it seems, that hsdev unable to scan this file: `/home/jip/Code/Haskell/petProject/src/Main.hs`
Can you try this command: `hsinspect /home/jip/Code/Haskell/petProject/src/Main.hs`?

**Comment by Jipperism** [comment] 2016-01-23 23:19
This is the output of the command:

> {"location":{"project":null,"file":"/home/jip/Code/Haskell/petProject/src/Main.hs"},"inspection":{"flags":[],"mtime":1453590474},"module":{"location":{"project":null,"file":"/home/jip/Code/Haskell/petProject/src/Main.hs"},"name":"Main","declarations":[{"pos":{"line":5,"column":1},"name":"main","decl":{"what":"function","type":"IO ()"}},{"pos":{"line":8,"column":1},"name":"test","decl":{"what":"function","type":"[Integer] -> Integer"}}]}}

After restarting sublime these messages did not show up again (also the unknown includes seem to be gone now. I'm trying to reproduce them as we speak.

**Comment by mvoidex** [comment] 2016-01-23 23:24
Ok, let me know, if something goes wrong. I'll close this issue

**Closed by mvoidex** 2016-01-23 23:24 UTC

**Comment by Jipperism** [comment] 2016-01-24 12:38
Yesterday my installation worked for a brief moment but somehow it stopped working again after 30 minutes of trying out SH's features. hsdev and ghc-mod seem to be working correctly but when invoked together freeze my terminal.

hsdev run has also produced different output without an error message but I do not know how to reproduce it. My SublimeHaskell plugin has since stopped working. The command `hsdev ghc-mod lint src/Main.hs` freezes the prompt completely. I have tried setting up a new cabal project to start fresh but it didn't help either. Is there anyway I can give you some more helpful output?

From project directory:
```
$ hsdev scan --cabal
{"notify":[{"status":"working","progress":null,"name":"cabal","task":"scanning","type":"cabal"}]}
{"notify":[{"status":"ok","progress":null,"name":"cabal","task":"scanning","type":"cabal"}]}
[]

$ hsdev scan --project ~/Code/Haskell/petProject
{"notify":[{"status":"working","progress":null,"name":"petProject","task":"scanning","type":"project"}]}
{"notify":[{"status":"working","progress":null,"name":"petProject","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"/home/jip/Code/Haskell/petProject","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":null,"name":"petProject","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"/home/jip/Code/Haskell/petProject","task":"scanning","type":"path"}]}
{"notify":[{"status":"ok","progress":null,"name":"petProject","task":"scanning","type":"project"}]}
[]

$ hsdev ping
{"message":"pong"}

$hsdev run
24/01/16 13:30:28 +0100	INFO	> Log politics: low = Info, high = Warning
hsdev: bind: resource busy (Address already in use)
24/01/16 13:30:28 +0100	INFO	hsdev> Server started at port 4567
hsdev: <<loop>>
exception thread blocked indefinitely in an MVar operation

$ hsinspect /home/jip/Code/Haskell/petProject/src/Main.hs
{"location":{"project":null,"file":"/home/jip/Code/Haskell/petProject/src/Main.hs"},"inspection":{"flags":[],"mtime":1453638810},"module":{"location":{"project":null,"file":"/home/jip/Code/Haskell/petProject/src/Main.hs"},"name":"Main","declarations":[{"pos":{"line":5,"column":1},"name":"main","decl":{"what":"function","type":"IO ()"}},{"pos":{"line":8,"column":1},"name":"test","decl":{"what":"function"}}]}}

$ ghc-mod lint src/Main.hs 
src/Main.hs:8:8: Warning: Redundant bracketFound:  sum . (take 5)Why not:  sum . take 5

```
ST3 startup console output:
```
DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/jip/.config/sublime-text-3/Packages
state path: /home/jip/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/jip/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage", "Vintageous"]
pre session restore time: 0.109562
startup time: 0.246841
first paint time: 0.286109
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeGit.SublimeGit
reloading plugin SublimeHaskell.autobuild
reloading plugin SublimeHaskell.autocomplete
reloading plugin SublimeHaskell.cabal
reloading plugin SublimeHaskell.cabalbuild
reloading plugin SublimeHaskell.cache
reloading plugin SublimeHaskell.fix_syntax
reloading plugin SublimeHaskell.ghci
reloading plugin SublimeHaskell.ghcmod
reloading plugin SublimeHaskell.haskell_docs
reloading plugin SublimeHaskell.haskell_type
reloading plugin SublimeHaskell.hdevtools
reloading plugin SublimeHaskell.hdocs
reloading plugin SublimeHaskell.hsdev
reloading plugin SublimeHaskell.parseoutput
reloading plugin SublimeHaskell.repl
reloading plugin SublimeHaskell.stylishhaskell
reloading plugin SublimeHaskell.sublime_haskell_common
reloading plugin SublimeHaskell.symbols
reloading plugin SublimeHaskell.util
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin Terminal.Terminal
reloading plugin User.toggle_vintageous
plugins loaded
Sublime Haskell: Starting hsdev server
Sublime Haskell: connecting to hsdev server...
Sublime Haskell: connecting to hsdev server...
Sublime Haskell: connected to hsdev server
Sublime Haskell: connected to hsdev server
Package Control: Skipping automatic upgrade, last run at 2016-01-24 12:48:27, next run at 2016-01-24 13:48:27 or after
```

**Comment by mvoidex** [comment] 2016-01-24 14:17
hsdev: <<loop>>

I've found similar bug on Ubuntu in `simple-log` yesterday, but I was hoping, that it's not critical.
Try [hsdev-0.1.5.4](http://hackage.haskell.org/package/hsdev-0.1.5.4)

**Comment by mvoidex** [comment] 2016-01-24 14:22
No, it's not fixed yet
Trying to figure it out

**Comment by Jipperism** [comment] 2016-01-24 14:24
Ok, I'll be available if you need testing.

**Comment by Jipperism** [comment] 2016-01-24 14:32
`$ hsdev run
24/01/16 15:29:12 +0100	INFO	> Log politics: low = Info, high = Warning
hsdev: bind: resource busy (Address already in use)
24/01/16 15:29:12 +0100	INFO	hsdev> Server started at port 4567
hsdev: <<loop>>
exception thread blocked indefinitely in an MVar operation

$ hsdev run --port 7654
24/01/16 15:29:27 +0100	INFO	> Log politics: low = Info, high = Warning
24/01/16 15:29:27 +0100	INFO	hsdev> Server started at port 7654

$ hsdev run --port 7654
24/01/16 15:30:24 +0100	INFO	> Log politics: low = Info, high = Warning
hsdev: bind: resource busy (Address already in use)
24/01/16 15:30:24 +0100	INFO	hsdev> Server started at port 7654
hsdev: <<loop>>
exception thread blocked indefinitely in an MVar operation
```

Changing the port number makes the servers run (or at least not crash, I cannot stop the process however and have to forcequit my terminal). Running on the same port again after forcing the terminal to quit makes the error reappear.

**Comment by mvoidex** [comment] 2016-01-24 14:37
Port 4567 is already in use by `hsdev start`, thats why `hsdev run` fails, but this instance of `hsdev start` doesn't respond due to some reasons. When I killed it (`kill -9 pid`) and restarted - all seems to be ok.

**Comment by Jipperism** [comment] 2016-01-24 15:00
I just got it to work again (did not upgrade to 0.1.5.4 yet). After killing the process and using `hsdev stop` I could start the server manually through terminal (`hsdev start`, is it necessary to do this manually?) and then `hsdev ghc-mod lint src/Main.hs` completed succesfully and sublimehaskell seems to be working again.

**Comment by mvoidex** [comment] 2016-01-24 15:02
Killing process must be enough, Sublime will restart it

**Comment by Jipperism** [comment] 2016-01-24 15:27
Just killing the process doesn't seem to work. I can get it to work now by starting the server manually, and checking if `hsdev ghc-mod lint src/Main.hs` is working. If it is, sublime will work as well. If I exit ST3, the process does not seem to be shut down (`hsdev start --port 4557`). If I shut it down, and then start the server manually it works again. Can this point you to the bug a little?

**Comment by mvoidex** [comment] 2016-01-24 15:29
Thanks a lot for help. I'll fix some bugs I've found and then will test it on Ubuntu

**Comment by mvoidex** [comment] 2016-01-31 17:27
I've uploaded [hsdev-0.1.5.5](http://hackage.haskell.org/package/hsdev-0.1.5.5) with some fixes.
Please test it when you have some time

**Comment by Jipperism** [comment] 2016-01-31 18:37
Hi, I have tested version 0.1.5.5 and some things still seem to be wrong. SublimeHaskell + hsdev only seem to work when I `$hsdev run` and start up sublime. When I exit sublime hsdev gives a rather long exit message. After closing sublime I need to `$hsdev stop` and as soon as the process is gone, I can start over again. Just starting sublime does not seem to work. Thanks for the bugfixes anyway, maybe there is something wrong with my own setup if you don't experience these problems anymore?

**Comment by mvoidex** [comment] 2016-02-01 11:26
Do you have `Sublime Haskell: Starting hsdev server` in Sublime console? And, if any, what goes after it?

**Comment by Jipperism** [comment] 2016-02-01 12:14
This is the output if I start ST3 without starting starting the hsdev server manually:

```
Sublime Haskell: Starting hsdev server
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: failed to connect to hsdev server
Sublime Haskell: failed to connect to hsdev server
Sublime Haskell: connecting to hsdev server (1)...
Sublime Haskell: connecting to hsdev server (1)...
Sublime Haskell: connected to hsdev server
Sublime Haskell: connected to hsdev server
```
So it seems to connect in the end, although it sometimes needs up to 7 or 8 tries. It did this before the last patch as well. If I start hsdev server manually by `$ hsdev run` it's all working and this is the ST3 console output:

```
Sublime Haskell: Starting hsdev server
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: failed to connect to hsdev server
Sublime Haskell: connected to hsdev server
Sublime Haskell: Inspection failed: 'HsDev' object has no attribute 'hsdev_socket'
Sublime Haskell: loading standard modules info for cabal failed with 'HsDev' object has no attribute 'hsdev_socket'
Sublime Haskell: connecting to hsdev server (1)...
Sublime Haskell: connected to hsdev server
```

Another important detail might be that I have to do `$ hsdev run` from the same directory as where my cabal file resides, otherwise it still isn't working.

**Comment by mvoidex** [comment] 2016-02-01 12:27
Thanks

> So it seems to connect in the end

And it still doesn't work in this case?

> Another important detail might be that I have to do $ hsdev run from the same directory as where my cabal file resides, otherwise it still isn't working.

Thanks, I'll try to reproduce it

**Comment by Jipperism** [comment] 2016-02-01 12:48
No, it still doesn't work in that case.

**Comment by mvoidex** [comment] 2016-02-01 13:17
Very strange
Can you test `$hsdev ping` from terminal and these commands from Sublime console:

    import SublimeHaskell.autocomplete as a
    a.hsdev_client.ping()

**Comment by Jipperism** [comment] 2016-02-01 13:29
```
Jipperism~$ hsdev ping
{"error":"connect: does not exist (Connection refused)","details":{}}
Jipperism~$ hsdev start
Server started at port 4567
Jipperism~$ hsdev ping
{"error":"connect: does not exist (Connection refused)","details":{}}
Jipperism~$ hsdev run
01/02/16 14:24:29 +0100	INFO	> Log politics: low = Info, high = Warning
01/02/16 14:24:29 +0100	INFO	hsdev> Server started at port 4567
01/02/16 14:24:34 +0100	INFO	<socket: 23>> <socket: 23> connected
01/02/16 14:24:34 +0100	INFO	<socket: 23>> <socket: 23> disconnected
01/02/16 14:24:34 +0100	TRACE	<socket: 23>>  => {"command":"ping","current-directory":"/home/jip","silent":false,"no-file":false,"id":null,"timeout":0}
01/02/16 14:24:34 +0100	ERROR	<socket: 23>> exception: user error (Receive chan closed)
```
In different terminal:
```
Jipperism~$ hsdev ping
{"message":"pong"}
```
In ST3 console:
```
>>> import SublimeHaskell.autocomplete as a
>>> a.hsdev_client.ping()
True
```
SublimeHaskell was not working while I called a.hsdev_client.ping().

**Comment by mvoidex** [comment] 2016-02-01 13:53
Does `hsdev start` from terminal always fails to start server (i.e. `hsdev ping` fails after `hsdev start` and works only if you run `hsdev run`)?
If yes, try this:

    hsdev start --log-config "use trace" --log hsdev.log
    hsdev ping
    hsdev stop
    cat hsdev.log

**Comment by mvoidex** [comment] 2016-02-15 18:32
I think this bug is fixed in 0.1.6.1

**Comment by Jipperism** [comment] 2016-02-27 15:54
Hi! Sorry for my late reply, i have been very busy lately. I reinstalled hsdev as well as sublimehaskell and now everything seems to be working perfectly! Awesome man, thanks a lot, I'll play around with it some more today.

**Comment by mvoidex** [comment] 2016-02-27 16:36
Great
